### ISSUE TITLE
Problem with code formatting on ereader (epub)

### ISSUE THREAD

**Issue by javl** [nature-of-code/noc-book#103]
I was wondering what devices the epub version of the book has been tested on.
On my Kobo Aura the code blocks don't get formatted the right way, with weird gaps and alignment. With a bit of effort you can still read it, but it's not as clean as could be. 
Before I look further into this it would be useful to know for what screen size the epub has been optimized.
Or could this be an issue with the tool you use for converting the files, instead of your formatting?

Also, I was wondering how often the new files pdf/epub are generated, as I have come across multiple errors in the book (downloaded last week) which have already been fixed in the repo.
I can of course build the latest .pdf myself, but the repo doesn't seem to contain a layout to generate the epub.

**Comment by shiffman** [comment]
it hasn't been updated for a long time but i am actively working on a new version with a new design system, hopefully it will improve.   I am not sure what the epub version is optimized for sadly, this was generated by a 3rd party company I used to make one from the HTML version. For corrections, you can check the repo version first yes!

**Comment by shiffman** [comment]
I'm going to close this issue, having an ePub version is a desired goal for the 2nd edition, but we are revamping the build process so may take some time to get to it.
