### ISSUE TITLE
1.6 broken link

### ISSUE THREAD

**Issue by javl** [nature-of-code/noc-book#104]
In chapter I.6 Perlin Noise (A Smoother Approach) there is a reference to the website of Ken Perlin (under the header "Noise Detail").

```
An online lecture by Ken Perlin lets you learn more about how
noise works from Perlin himself (http://www.noisemachine.com/talk1/).
```

This website is currently down (for maintenance it seems). You might want to check if it will come back online with the same info or if it will be changed.

**Comment by shiffman** [comment]
Couldn't find this site online anymore so just changed to Ken Perlin's noise page.

https://mrl.nyu.edu/~perlin/doc/oscar.html
