### ISSUE TITLE
4.13 live sketches not working

### ISSUE THREAD

**Issue by javl** [nature-of-code/noc-book#106]
The two sketches at the start of 4.13 Image Textures and Additive Blending do not show.
I think this is because of the missing image file used for the particle effects:
http://natureofcode.com/book/chapter-4-particle-systems/processingjs/chapter04/_4_08_ParticleSystemSmoke/data/texture.png

The file does seem to exist in the repo, at https://github.com/shiffman/The-Nature-of-Code/blob/master/noc_html/processingjs/chapter04/_4_08_ParticleSystemSmoke/data/texture.png

**Comment by shiffman** [comment]
This will change once the new build system with p5.js is in place.
