### ISSUE TITLE
Example 1.1 Minor Suggestion

### ISSUE THREAD

**Issue by goodsignal** [nature-of-code/noc-book#114]
When you switch to floating point numbers, it might be really nice to add a hint, reminder, or comment to adjust the data types for x and y to match. 

As a new coder, this tripped me up because under the mismatched data types, the random walk became a negatively biased walk.

**Comment by ssrajpurohit** [comment]
It is still negatively biased.

**Comment by shiffman** [comment]
Moving the book to p5.js so hopefully this won't be necessary since there isn't a distinction between int and float!
