### ISSUE TITLE
Normal Force Direction

### ISSUE THREAD

**Issue by drguildo** [nature-of-code/noc-book#115]
In section 2.7 it says:

> where the object is moving along a surface at an angle, computing the normal force is a bit more complicated because it doesn’t point in the same direction as gravity

but from reading the preceding paragraph it's made to sound like, generally and when there isn't a slope, the normal force would point in the opposite direction to gravity:

> The vehicle pushes down against the road with gravity, and Newton’s third law tells us that the road in turn pushes back against the vehicle. That’s the normal force.

**Comment by shiffman** [comment]
I've improved this a little bit (I think).
