### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by drguildo** [nature-of-code/noc-book#118]
Trying to build the book on Windows I get the following output:

```
$ magicbook build
Config file detected: magicbook.json
image not found in source folder: intro/intro_ex01.png
image not found in source folder: intro/intro_01.png
image not found in source folder: intro/intro_ex02.png
✂
image not found in source folder: chapter10/ch10_16.png
image not found in source folder: chapter10/ch10_ex04.png
image not found in source folder: chapter10/ch10_exc05.png
Prince XML error
```

While the `build` directory is populated with files, all the images etc. are broken.

[errors.txt](https://github.com/shiffman/The-Nature-of-Code/files/558361/errors.txt)

**Comment by aoozdemir** [comment]
I get the same error, except image sources.

```
$ magicbook build
Config file detected: magicbook.json
Prince XML error
```

**Comment by aoozdemir** [comment]
Ok. I think I've determined the problem here. When I run `magicbook build --config=./magicbook_all.json`, I get this error. 

````
$ magicbook build --config=./magicbook_all.json
Config file detected: ./magicbook_all.json
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /mnt/c/Users/AhmetOguzhan/Desktop/Pub/NOC/The-Nature-of-Code/noc_pdf/stylesheets/print.css
    at Glob.<anonymous> (/usr/lib/node_modules/magicbook/node_modules/glob-stream/index.js:41:11)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/usr/lib/node_modules/magicbook/node_modules/glob-stream/node_modules/glob/glob.js:172:8)    at done (/usr/lib/node_modules/magicbook/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/usr/lib/node_modules/magicbook/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /usr/lib/node_modules/magicbook/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/usr/lib/node_modules/magicbook/node_modules/glob-stream/node_modules/glob/glob.js:736:12)    at lstatcb_ (/usr/lib/node_modules/magicbook/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
```

All the stylesheets files are missing.

**Comment by nikookni** [comment]
Same error build on Ubuntu.
After investigation i downloaded and installed libpng12-0
http://packages.ubuntu.com/xenial/libpng12-0
Works perfectly now !

**Comment by kkshmz** [comment]
Hi guys, you need to download prince xml via http://www.princexml.com/download/
Can be also done from brew `brew cask install prince`

See reference here.
https://github.com/shiffman/The-Nature-of-Code/issues/137#issuecomment-330720154

**Comment by domisolsi** [comment]
(Windows10)
All done right (prince installed) : 
images always not linked at building 
`Sun Feb 18 10:39:15 2018: ---- begin
Sun Feb 18 10:39:16 2018: build/build1/intro/intro_ex01.png: warning: can't open input file: No such file or directory
Sun Feb 18 10:39:16 2018: build/build1/intro/intro_01.png: warning: can't open input file: No such file or directory
Sun Feb 18 10:39:16 2018: build/build1/intro/intro_ex02.png: warning: can't open input file: No such file or directory
Sun Feb 18 10:39:16 2018: build/build1/intro/intro_ex03.png: warning: can't open input file: No such file or directory` 
in build1 and 2,  HTML img tag should point to the image files that are in assets directory but without /assets/ !?
In build1 dir, If I move all the files in assets/, down a dir level, le links work fine in consolidated.html
So I did the same in build2 to get a better looking with html version but html files are not consolidated in this dir.
Is there a way to get pdf version build with all the images?
(I bought version 1.0 on line in july 2016)
Thanks a lot for your reply
(sorry for my English)
DoMi

**Comment by domisolsi** [comment]
Prince (used as app) tell me at compiling there is a problem with too long dir names...
perhaps a track?

**Comment by shiffman** [comment]
Please follow [noc-book-2](https://github.com/nature-of-code/noc-book-2) for the new build system!
