### ISSUE TITLE
Mistake in The Nature of Code book

### ISSUE THREAD

**Issue by simon-tiger** [nature-of-code/noc-book#133]
I came across a mistake in [Chapter 2](http://natureofcode.com/book/chapter-2-forces/) Example 2.5 (Fluid resistance): `movers[i] = new Mover(random(0.1,5),0,0);` should be `movers[i] = new Mover(random(0.1,5),i*20,0);`

**Comment by shiffman** [comment]
Thank you @simon-tiger!
