### ISSUE TITLE
Missing explanation

### ISSUE THREAD

**Issue by PPrasai** [nature-of-code/noc-book#134]
In the first "Introduction" chapter, there is this piece of code to ascertain the next step of the Walker:

```
void step() {
    float stepx = random(-1, 1);
    float stepy = random(-1, 1);

    x += stepx;
    y += stepy;
}
```

For some reason, the next step is always drawn relatively to the top-left of current location and the Walker heads in the general direction towards the top-left of the window. Some explanation about why the Walker's behaving like that would be very much appreciated!

**Comment by shiffman** [comment]
Addressed in noc-book-2 now.
