### ISSUE TITLE
Translation Questions

### ISSUE THREAD

**Issue by ofenerci** [nature-of-code/noc-book#136]
I would like to translate the book into Turkish. But I was unable to find the source files of the book. When I looked into the `chapters` folder, it is all about `html` files. 

Second issue is that which tools are necessary for translations: 
The first version of the book was written by Asciidoc and the second version by Magicbook. Is there an advantage choosing Magicbook over Asciidoc. It looks Asciidoc is a better alternative than Magicbook (or other markup alternatives such as Sphinx). 

How was the book made interactive in the [book side](http://natureofcode.com/)? So this issue could help for people who would like to translate the book.

**Comment by kkshmz** [comment]
Hi, to build the book and create the pdf, if you are on mac,
1. You need to git clone the repo
2. You need to install the required npm modules via `npm install` in the directory
3. You need to have [princexml](http://www.princexml.com/download/) installed via the link or with brew with `brew cask install prince`. [Reference issue](https://github.com/shiffman/The-Nature-of-Code/issues/137#issuecomment-330720154)
4. Build magicbook with `magicbook build` in directory
5. Find Consolidated.pdf in build files.

**Comment by shiffman** [comment]
I'll revisit translations once the new build system and 2nd edition is complete!
