### ISSUE TITLE
3.9 Typos

### ISSUE THREAD

**Issue by frankbass** [nature-of-code/noc-book#142]
page 128 
reads: "Since the force of gravity (Fp)" should read: "(Fg)"
illustration: "sin(theta)= Fg/Fp"  should read:"sin(theta)=Fp/Fg"
  
page 130
illustration: "sin(theta)=y/r  cos(theta)=x/r" should read: "sin(theta)=x/r cos(theta)=y/r"

**Comment by shiffman** [comment]
The illustrations are covered in other issues and the text has been fixed!
