### ISSUE TITLE
Issues to be Closed

### ISSUE THREAD

**Issue by nonas-hunter** [nature-of-code/noc-book#148]
There are a bunch of issues that have been fixed and can now be closed. I have made a list of them below. The list is ongoing and as more commits are made I will continue posting issues to close.

**Issues to be Closed**
#136 
#124
#122
#121
#120
#119
#110
#94
#45

In addition, many issues discuss similar topics- everyone seems to comment about Figure 3.13 which has an incorrect formula. I will work on finding these overlapping issues and closing them.

**Comment by shiffman** [comment]
Thanks so much for working on this last summer @nonas-hunter!
