### ISSUE TITLE
confused exponentially with parabolic

### ISSUE THREAD

**Issue by ghost** [nature-of-code/noc-book#162]
page 17
reads: "Can you map the probability <i>exponentially</i>-i.e. making the likelihood that a value is picked equal to the value squared?" should read:"... <b>parabolic</b>-i.e. making..."

Because exponential means something like f(x)=a^x (with "a" being some arbitrarily value)

**Comment by shiffman** [comment]
I have changed this to:

> Can you map the probability to a quadratic function
