### ISSUE TITLE
Broken Example Link : chapter-6-autonomous-agents

### ISSUE THREAD

**Issue by anuraghazra** [nature-of-code/noc-book#163]
Broken Example Link in **6.6 Flow Fields**

the demo is broken 

https://natureofcode.com/book/chapter-6-autonomous-agents/

```
GET https://natureofcode.com/book/processingjs/chapter06/_6_04_Flowfield/Flowfield.pde 404
```

![natureofcodelinkerror](https://user-images.githubusercontent.com/35374649/50840205-fc8b2180-1387-11e9-9067-3beb8d584d3d.png)

**Comment by shiffman** [comment]
We are actively rebuilding the PDF and website generation system and changing the examples over to p5.js so this should get fixed during that process! Follow https://github.com/nature-of-code/noc-book-2
