### ISSUE TITLE
Chapter 5 toxiclibs function unknown

### ISSUE THREAD

**Issue by abauville** [nature-of-code/noc-book#165]
The line 
physics.addBehavior(new GravityBehavior(new Vec2D(0,0.5)));

returns "The class "GravityBehavior" does not exist"
It works fine with GravityBehavior2D, instead
Using processing 3.5.3 and the version of toxiclibs from the library

**Comment by shiffman** [comment]
I believe this has been fixed in https://github.com/nature-of-code/noc-examples-processing, if not please feel free to flag an issue there!
