### ISSUE TITLE
Broken image link on figure 1.10 - Chapter 1: Vectors

### ISSUE THREAD

**Issue by ghost** [nature-of-code/noc-book#24]
On the website, the image for figure 1.10 doesn't load in [Chapter 1: Vectors](http://natureofcode.com/book/chapter-1-vectors/):

``` html
<img src="imgs/chapter01/ch01_10.png" alt="Nature of Code Image">
```

Based on the other image paths on the page, I think it's just missing `/book/` at and start so it should be:

``` html
<img src="/book/imgs/chapter01/ch01_10.png" alt="Nature of Code Image">
```

**Comment by shiffman** [comment]
Going to close this one as image paths and the build process is being re-booted in [noc-book-2](https://github.com/nature-of-code/noc-book-2)
