### ISSUE TITLE
Figure 7.11

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book#35]
Has a stray 1 on generation 0.

**Comment by jschulenklopper** [comment]
Corrected in commit e9f7384, present in PR #65.

**Comment by shiffman** [comment]
Leaving open until I fix the original AI file.

**Comment by shiffman** [comment]
Going to open a new issue in [noc-book-2](https://github.com/nature-of-code/noc-book-2/issues) since transferring this one may affect link to commit and PR.

**Comment by shiffman** [comment]
Actually, never mind, I just went ahead and fixed the AI file!
