### ISSUE TITLE
Code demos still running when off-screen

### ISSUE THREAD

**Issue by elliotcm** [nature-of-code/noc-book#47]
First off this is a great book.  I've been trying to get to grips with the physics of vectors and force for years now and this is the first presentation of the topic that has actually made sense to me.

One small request; your in-browser code examples, while helpful, eat up a lot of CPU and thus laptop battery power.  They only kick off once they scroll into view, which is great, but they keep going once you've scrolled past them.

Since some of the chapters are very long I tend to wind up leaving the tab open for days at a time.  Since they contain numerous running code examples this can add up to a lot of wasted cycles and quickly drained batteries unless I remember to refresh the page or manually pause each example as I go.

Could you alter the JS used to run the examples so that they pause execution when you scroll them off-screen?

**Comment by shiffman** [comment]
Thanks, I agree this is a key feature to implement.  I'm stuck on hold for a bit as I've got to get the book  (PDF and HTML) building again using a new system.  Hope this will come alive again soon.

**Comment by elliotcm** [comment]
:+1: 

I've knocked together a WIP branch here to save you some time: https://github.com/shiffman/The-Nature-of-Code-archive/compare/master...elliotcm:patch-1

**Comment by shiffman** [comment]
Awesome, the archive repo is no longer in play. . however, if you want to submit a pull request directly to https://github.com/shiffman/natureofcode.com I'll take it!

**Comment by shiffman** [comment]
Will need to revisit with new magic book system.

**Comment by shiffman** [comment]
I'm going to close this as we are re-inventing the build system and way of displaying sketches (embedded p5.js) and hopefully we'll have this feature as part of the new materials.
