### ISSUE TITLE
inline <code>

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book#94]
For the 1st edition, I did something rather odd.  I thought I might want to differentiate inline references to functions, variables, classes, etc.  And I ended up with something like this.

``` html
This <span class="function">draw()</span> function loops over and over.  A <span
class="klass">Particle</span> object has variables <span class="var">x</span> and 
<span class="var">y</span>.
```

This now seems rather silly.  I propose doing a global find/replace:
- `<span class="function">something</span>` → `<code>something</code>`
- `<span class="klass">something</span>` → `<code>something</code>`
- `<span class="var">something</span>` → `<code>something</code>`

Seem reasonable? @runemadsen @alterebro

**Comment by alterebro** [comment]
Totally, I'd only keep them in case you are planning to style them differently on the HTML version, even in that case it'd be better to have the `<code>` tag instead of `<span>`

**Comment by shiffman** [comment]
I don't think it's worth the trouble of maintaining, happy to just have a single `<code>` style.  See the above 3 commits where I did a global find replace.  Go ahead and adjust the CSS accordingly.  Feel free to let me know if it looks like I messed everything up and we can revert.

**Comment by alterebro** [comment]
Perfect, nothing looks messed up.

**Comment by shiffman** [comment]
I believe this is all set!
